<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\EventTickets\Block\Adminhtml\Product\Edit\Tab\Space\StepWizardConfiguration */
?>
<?= /* @noEscape */ $block->renderSpaceWizardSteps(['configurableModal' => 'product_form.product_form.awEtSpaceConfigurationModal']) ?>
<script>
    require(['jquery', 'uiRegistry', 'underscore'], function ($, registry, _) {
        $('body').trigger('contentUpdated');
        $('.<?= /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=steps-wizard-main]').applyBindings();

        registry.async('<?= /* @noEscape */ $block->getData('config/stepWizardName') ?>')(function (component) {
            _.delay(component.open.bind(component), 500);
        })
    });
</script>
