<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\EventTickets\Block\Ticket\Management\Info */
$ticket = $block->getTicketInfo();
?>
<?php if ($ticket): ?>
    <br/>
    <fieldset class="fieldset ticket-info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Ticket Information')) ?></span></legend>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Ticket Status:')) ?></span>
            <span class="value"><?= $block->escapeHtml($block->getTicketStatusTitle($ticket->getStatus())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Ticket Type:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getTicketTypeStorefrontTitle()) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Sector:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getSectorStorefrontTitle()) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Ticket Number:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getNumber()) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Event Title:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getEventTitle()) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Event Start Date:')) ?></span>
            <span class="value">
                <?= /* @noEscape */ $block->formatDate($ticket->getEventStartDate(), \IntlDateFormatter::MEDIUM, true) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Event End Date:')) ?></span>
            <span class="value">
                <?= /* @noEscape */ $block->formatDate($ticket->getEventEndDate(), \IntlDateFormatter::MEDIUM, true) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Order:')) ?></span>
            <span class="value"><?= $block->escapeHtml($block->getOrderNumber($ticket->getOrderId())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Attendee Name:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getAttendeeName()) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Attendee Email:')) ?></span>
            <span class="value"><?= $block->escapeHtml($ticket->getAttendeeEmail()) ?></span>
        </div>
    </fieldset>

    <?php if ($block->isAllowUndoCheckIn($ticket)): ?>
        <form action="<?= $block->escapeUrl($block->getUrl('aw_event_tickets/ticket/management_undoCheckIn')) ?>"
              method="post">
            <input type="hidden" name="ticket_number" value="<?= $block->escapeHtml($ticket->getNumber()) ?>"/>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?= $block->escapeHtml(__('Undo Check In')) ?>"
                            class="action primary undo-check-in-ticket">
                        <span><?= $block->escapeHtml(__('Undo Check In')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    <?php endif; ?>
<?php endif; ?>
