<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\EventTickets\Block\Product\View */
$product = $block->getProduct();
?>
<?php if ($product->getAwEtScheduleType() == $block->getRecurringType()): ?>

    <div class="aw_et-calendar-container">
        <?php if ($block->getFilterFlag()): ?>
            <div data-bind="scope: 'awEtFilterByTicketQty'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        <?php endif; ?>
        <div data-bind="scope: 'awFullCalendarComponent'">
            <div class="aw_et-calendar"></div>
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>
<?php endif; ?>
<div data-role="aw-et-view-options" class="aw-et-view-options-wrapper">
    <div class="options-container">
        <div data-bind="scope: 'awEtViewOptions'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>
    <div class="summary-container">
        <div data-bind="scope: 'awEtViewSummary'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <?= $block->getChildHtml('add_to_cart_button'); ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-et-view-options]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>
<script type="text/javascript">
    require([
        'jquery',
        'uiRegistry',
        'jquery/ui',
        'jquery/validate',
        'mage/mage'
    ], function ($, registry) {
        'use strict';

        $.validator.setDefaults({ ignore: '[data-aw-ignore=true]', focusInvalid: false });
        $.validator.addMethod(
            'aw-et-ui-options-validate', function (value) {
                var awEtViewOptions = registry.get('awEtViewOptions');

                if (awEtViewOptions) {
                    return awEtViewOptions.validate();
                }
                return true;
            },
            ''
        );

    });
</script>
