<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\EventTickets\Block\Adminhtml\Product\Space\Steps\SelectSpace */
?>
<div class="aw-et-select-space-block">
    <h2 class="steps-wizard-title">
        <?= $block->escapeHtml(__('Step 2: Select Space')); ?>
    </h2>
    <div data-bind="scope: 'aw_event_tickets_space_listing_container'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "aw_event_tickets_space_listing_container":{
                        "type":"fieldset",
                        "name":"aw_event_tickets_space_listing_container",
                        "config":{"label":"","collapsible":false,"componentType":"fieldset"},
                        "children":{
                            "aw_event_tickets_space_listing":{
                                "type":"container",
                                "name":"aw_event_tickets_space_listing",
                                "dataScope":"aw_event_tickets_space_listing",
                                "config":{
                                    "autoRender":true,
                                    "render_url": "<?= $block->escapeUrl($block->getUrl('mui/index/render/isWizard/true')) ?>",
                                    "update_url":"<?= $block->escapeUrl($block->getUrl('mui/index/render')) ?>",
                                    "realTimeLink":true,
                                    "dataLinks":{"imports":true,"exports":false},
                                    "component":"Magento_Ui/js/form/components/insert-listing",
                                    "externalProvider":"${ $.ns }.aw_event_tickets_space_listing_data_source",
                                    "ns":"aw_event_tickets_space_listing",
                                    "deps":["product_form.product_form_data_source"],
                                    "provider":"product_form.product_form_data_source",
                                    "loading":false,
	                                "isWizardFilter": true,
	                                "statusFilter": 1,
                                    "exports":{
                                        "isWizardFilter":"${ $.externalProvider }:params.isWizard",
                                        "statusFilter":"${ $.externalProvider }:params.spaceStatus"
                                    }
                                }
                            }
                        }
                    },
                    "<?= /* @noEscape */  $block->getComponentName() ?>": {
                        "component": "Aheadworks_EventTickets/js/product/new/space/steps/select-space",
                        "multiSelectName": "<?= /* @noEscape */ $block->getData('config/multiSelectName') ?>",
                        "spaceProviderName": "<?= /* @noEscape */ $block->getData('config/providerName') ?>",
                        "appendTo": "<?= /* @noEscape */  $block->getParentComponentName() ?>"
                    }
                }
            }
        }
    }
</script>
