<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\EventTickets\Block\Product\Listing\Renderer */
?>
<div class="aw-et__stock-status" title="<?= $block->escapeHtml(__('Availability')) ?>">
    <span><?= $block->escapeHtml($block->getStatus()) ?></span>
</div>
<div class="aw-et__start-date" title="<?= $block->escapeHtml(__('Start Date')) ?>">
    <span><?= $block->escapeHtml($block->getStartDate()) ?></span>
</div>
